[project]
name = "jangal"
version = "0.0.1"
description = "trees, forests, graphs"
requires-python = ">=3.8"
dependencies = [
    "pytest>=6.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
