name: "Python Tests"

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "**.py"
            - ".github/workflows/python-tests.yml"
    pull_request:
        branches: [main]
        paths:
            - "**.py"
            - ".github/workflows/python-tests.yml"
    release:
        types: [created]
    schedule:
        - cron: "0 0 * * 0"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Pre-Commit Hooks
              uses: pre-commit/action@main

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Install dependencies
              working-directory: src/python/
              run: uv sync

            - name: Run Tests
              working-directory: src/python/
              run: uv run python -m pytest
